Repository openfun/ralph, pull requests merged in 2021-01, with the labels that each got.

#43 🔖(major) first major release 1.0.0
  CHANGELOG.md
  setup.cfg
Labels: FUN, needs review

#44 💚(circle) fix docker login step
  .circleci/config.yml
Labels: bug, needs review

#45 🔥(cli) remove click_log
  CHANGELOG.md
  setup.cfg
  src/ralph/cli.py
  src/ralph/utils.py
  tests/test_cli.py
Labels: bug

#49 💚(circle) allow docker hub anonymous mode
  .circleci/config.yml
Labels: improvement, needs review
