Repository openfun/ralph, pull requests merged in 2021-03, with the labels that each got.

#70 🐛(tray) remove version immutable field in selector
  CHANGELOG.md
  src/tray/templates/services/app/dc.yml.j2
Labels: bug, needs review

#66 ModelSelector
  CHANGELOG.md
  src/ralph/defaults.py
  src/ralph/exceptions.py
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/base.py
  src/ralph/models/edx/browser.py
  src/ralph/models/edx/server.py
  src/ralph/models/selector.py
  src/ralph/utils.py
  tests/models/test_selector.py
  tests/test_utils.py
Labels: WIP, feature

#77 ✅(tests) rename tests
  tests/backends/database/test_es.py
  tests/backends/storage/test_base.py
  tests/backends/storage/test_fs.py
  tests/backends/storage/test_ldp.py
  tests/backends/storage/test_swift.py
  tests/backends/test_mixins.py
  tests/fixtures/backends.py
  tests/fixtures/edx/base.py
  tests/fixtures/edx/browser.py
  tests/fixtures/edx/server.py
  tests/fixtures/logs.py
  tests/models/edx/test_base.py
  tests/models/edx/test_browser.py
  tests/models/edx/test_server.py
  tests/test_cli.py
  tests/test_defaults.py
  tests/test_filters.py
  tests/test_logger.py
  tests/test_parsers.py
  tests/test_utils.py
Labels: improvement

#85 🔒(project) add system package upgrades in docker image builds
  CHANGELOG.md
  Dockerfile
Labels: critical, needs review
