Repository openfun/ralph, pull requests merged in 2021-02, with the labels that each got.

#51 ✨(cli) allow to force push for database backends
  CHANGELOG.md
  src/ralph/backends/database/base.py
  src/ralph/backends/database/es.py
  src/ralph/cli.py
  tests/backends/database/test_es.py
Labels: improvement, needs review

#52 ✨(backends:es) add support for supported client options
  CHANGELOG.md
  src/ralph/backends/database/es.py
  src/ralph/cli.py
  tests/backends/database/test_es.py
  tests/test_cli.py
Labels: feature, needs review

#53 🔖(minor) bump release to 1.1.0
  CHANGELOG.md
  setup.cfg
  src/ralph/__init__.py
Labels: FUN

#54 📝(env) fix documentation of environment variables
  .env.dist
Labels: improvement, needs review

#55 🐛(tray) fix pods anti-affinity and missing secrets
  CHANGELOG.md
  src/tray/templates/services/app/dc.yml.j2
  src/tray/templates/services/app/secret.yml.j2
  src/tray/vars/vault/main.yml.j2
Labels: bug, needs review

#56 🚸(project) add issue and pull request templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Support_question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: improvement, needs review

#59 ✨(models) add edx server event model
  .pylintrc
  CHANGELOG.md
  setup.cfg
  src/ralph/backends/storage/ldp.py
  src/ralph/cli.py
  src/ralph/defaults.py
  src/ralph/models/__init__.py
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/base.py
  src/ralph/models/edx/server.py
  tests/backends/database/test_es.py
  tests/backends/storage/test_fs.py
  tests/backends/storage/test_ldp.py
  tests/fixtures/edx/base.py
  tests/fixtures/edx/server.py
  tests/models/__init__.py
  tests/models/edx/__init__.py
  tests/models/edx/test_base.py
  tests/models/edx/test_server.py
  tests/test_cli.py
Labels: WIP, feature

#61 ✨(models) add edX page_close browser event model
  CHANGELOG.md
  src/ralph/models/edx/browser.py
  tests/fixtures/backends.py
  tests/fixtures/edx/browser.py
  tests/models/edx/test_browser.py
Labels: WIP, feature

#63 ➖(parsers) remove pandas dependency in GELF parser
  CHANGELOG.md
  setup.cfg
  src/ralph/filters.py
  src/ralph/parsers.py
  tests/test_filters.py
  tests/test_parsers.py
Labels: improvement, needs review

#67 ✏️(project) fix docstring typos for ralph documentation
  src/ralph/cli.py
  src/ralph/defaults.py
  src/ralph/exceptions.py
  src/ralph/filters.py
  src/ralph/logger.py
  tests/fixtures/backends.py
  tests/test_cli.py
  tests/test_defaults.py
  tests/test_logger.py
  tests/test_parsers.py
  tests/test_utils.py
Labels: improvement, needs review

#60 📝(project) add base documentation
  .circleci/config.yml
  .env.dist
  .gitignore
  CHANGELOG.md
  LICENSE.md
  Makefile
  README.md
  docker-compose.yml
  docs/CHANGELOG.md
  docs/LICENSE.md
  docs/backends.md
  docs/commands.md
  docs/contribute.md
  docs/index.md
  docs/models/edx.md
  docs/models/index.md
  mkdocs.yml
  setup.cfg
Labels: feature, needs review

#68 ✨(tray) add support for ES cluster CA certs
  CHANGELOG.md
  src/tray/templates/services/app/cronjob_pipeline.yml.j2
  src/tray/templates/services/app/dc.yml.j2
  src/tray/templates/services/app/secret-es-ca.yml.j2
  src/tray/templates/services/app/secret.yml.j2
  src/tray/vars/all/main.yml
  src/tray/vars/vault/main.yml.j2
Labels: improvement, needs review

#69 🔖(minor) bump release to 1.2.0
  CHANGELOG.md
  setup.cfg
  src/ralph/__init__.py
Labels: FUN, needs review
