Repository openfun/ralph, pull requests merged in 2021-06, with the labels that each got.

#80 ✨(models) add edX server event to xAPI converter
  CHANGELOG.md
  src/ralph/exceptions.py
  src/ralph/models/converter.py
  src/ralph/models/edx/converters/__init__.py
  src/ralph/models/edx/converters/xapi/__init__.py
  src/ralph/models/edx/converters/xapi/base.py
  src/ralph/models/edx/converters/xapi/navigational.py
  src/ralph/models/edx/converters/xapi/server.py
  src/ralph/models/xapi/navigation/fields/objects.py
  src/ralph/utils.py
  tests/models/edx/converters/__init__.py
  tests/models/edx/converters/xapi/__init__.py
  tests/models/edx/converters/xapi/test_base.py
  tests/models/edx/converters/xapi/test_navigational.py
  tests/models/edx/converters/xapi/test_server.py
  tests/models/test_converter.py
  tests/test_utils.py
Labels: WIP, feature, needs review

#100 Converters cli
  .env.dist
  CHANGELOG.md
  src/ralph/cli.py
  src/ralph/defaults.py
  src/ralph/exceptions.py
  src/ralph/models/converter.py
  src/ralph/models/edx/converters/xapi/base.py
  src/ralph/models/edx/converters/xapi/navigational.py
  src/ralph/models/edx/converters/xapi/server.py
  tests/models/edx/converters/xapi/test_base.py
  tests/models/edx/converters/xapi/test_navigational.py
  tests/models/edx/converters/xapi/test_server.py
  tests/models/test_converter.py
  tests/test_cli.py
Labels: feature, needs review

#107 🔧(project) add potsie bridged network
  docker-compose.yml
Labels: improvement, needs review
