Repository openfun/ralph, pull requests merged in 2021-05, with the labels that each got.

#93 ✨(tray) move to k8s
  .circleci/config.yml
  CHANGELOG.md
  src/tray/templates/services/app/cronjob_pipeline.yml.j2
  src/tray/templates/services/app/deploy.yml.j2
  src/tray/templates/services/app/secret-es-ca.yml.j2
  src/tray/templates/services/app/secret.yml.j2
  src/tray/templates/volumes/history.yml.j2
Labels: feature, needs review

#94 ⚡️(tray) adjust probes configuration
  CHANGELOG.md
  src/tray/templates/services/app/deploy.yml.j2
Labels: improvement, needs review

#84 ✨(models) add xAPI page_viewed and page_terminated models
  CHANGELOG.md
  src/ralph/models/xapi/__init__.py
  src/ralph/models/xapi/base.py
  src/ralph/models/xapi/config.py
  src/ralph/models/xapi/constants.py
  src/ralph/models/xapi/fields/__init__.py
  src/ralph/models/xapi/fields/actors.py
  src/ralph/models/xapi/fields/objects.py
  src/ralph/models/xapi/fields/verbs.py
  src/ralph/models/xapi/page_terminated.py
  src/ralph/models/xapi/page_viewed.py
  tests/models/xapi/__init__.py
  tests/models/xapi/fields/__init__.py
  tests/models/xapi/fields/test_actors.py
  tests/models/xapi/fields/test_objects.py
  tests/models/xapi/fields/test_verbs.py
  tests/models/xapi/test_page_terminated.py
  tests/models/xapi/test_page_viewed.py
Labels: WIP, feature

#98 🎨(models) restructure navigation xapi models code structure
  src/ralph/models/xapi/fields/objects.py
  src/ralph/models/xapi/navigation/__init__.py
  src/ralph/models/xapi/navigation/fields/__init__.py
  src/ralph/models/xapi/navigation/fields/objects.py
  src/ralph/models/xapi/navigation/statements.py
  src/ralph/models/xapi/page_terminated.py
  src/ralph/models/xapi/page_viewed.py
  src/ralph/models/xapi/video/constants.py
  src/ralph/models/xapi/video/fields/contexts.py
  src/ralph/models/xapi/video/fields/results.py
  src/ralph/models/xapi/video/statements.py
  tests/models/xapi/fields/test_objects.py
  tests/models/xapi/test_navigation.py
  tests/models/xapi/test_page_terminated.py
  tests/models/xapi/test_page_viewed.py
  tests/models/xapi/test_video.py
Labels: improvement, needs review
