Repository openfun/ralph, pull requests merged in 2022-11, with the labels that each got.

#229 ✅(tests) fix hypothesis warnings
  tests/fixtures/hypothesis_configuration.py
  tests/fixtures/hypothesis_strategies.py
Labels: improvement, needs review

#234 🔖(minor) bump release to 3.1.0
  CHANGELOG.md
  setup.cfg
  src/ralph/__init__.py
  src/tray/tray.yml
Labels: needs review, FUN

#237 🔧(tray) add CA cert file path for the LRS ES backend
  CHANGELOG.md
  src/tray/templates/services/app/deploy.yml.j2
Labels: improvement
