Repository openfun/ralph, pull requests merged in 2023-01, with the labels that each got.

#252 :bug: Fix M1 Mac `make bootstrap` failures
  Dockerfile
Labels: needs review, bug

#202 ⬆️(project) upgrade base python version to 3.11
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  docs/index.md
  setup.cfg
  src/ralph/models/xapi/fields/common.py
Labels: FUN, dependencies

#259 🔖(minor) bump release to 3.2.0
  CHANGELOG.md
  setup.cfg
  src/ralph/__init__.py
  src/tray/tray.yml
Labels: needs review, FUN
