Repository openfun/ralph, pull requests merged in 2023-07, with the labels that each got.

#297 🏗️(backends) unify data backends s3
  .circleci/config.yml
  Dockerfile
  setup.cfg
  src/ralph/backends/data/s3.py
  tests/backends/data/test_s3.py
  tests/conftest.py
  tests/fixtures/backends.py
Labels: needs review, feature

#395 (api) enforce valid IRI with `GET /statements/?activity=`
  CHANGELOG.md
  src/ralph/api/routers/statements.py
  tests/api/test_statements_get.py
Labels: improvement, easy pick

#389 ♻️(backends) change how duplicate statement ids are handled
  CHANGELOG.md
  src/ralph/api/routers/statements.py
  src/ralph/backends/database/clickhouse.py
  src/ralph/backends/database/mongo.py
  tests/api/test_statements_post.py
  tests/api/test_statements_put.py
  tests/backends/database/test_mongo.py
Labels: improvement, needs review

#386 ✅(tests) use requests_mock fixture in LDPDataBackend tests
  setup.cfg
  tests/backends/data/test_ldp.py
Labels: improvement
