Repository openfun/ralph, pull requests merged in 2023-10, with the labels that each got.

#431 Clean converter Edx to xAPI code
  CHANGELOG.md
  src/ralph/models/edx/converters/xapi/base.py
  tests/models/edx/converters/xapi/test_base.py
  tests/models/edx/converters/xapi/test_enrollment.py
  tests/models/edx/converters/xapi/test_navigational.py
  tests/models/edx/converters/xapi/test_server.py
  tests/models/edx/converters/xapi/test_video.py
  tests/models/test_converter.py
Labels: improvement, needs review

#466 🐛(backends) fix default RALPH_BACKENDS__HTTP__LRS__HEADERS variable
  .env.dist
Labels: needs review

#460 🎨(tests) clean tests by factoring statements and renaming
  tests/api/test_statements_get.py
  tests/api/test_statements_post.py
  tests/api/test_statements_put.py
  tests/backends/http/test_async_lrs.py
  tests/fixtures/auth.py
  tests/helpers.py
  tests/test_helpers.py
Labels: improvement

#468 ✨(cli) sort backend arguments alphabetically
  CHANGELOG.md
  src/ralph/cli.py
  tests/test_cli_usage.py
Labels: improvement

#477 🐛(helm) fix clickhouse Helm's version
  CHANGELOG.md
  src/helm/ralph/Chart.yaml
Labels: improvement

#463 (api) Add option to enforce use of scopes (`all/read`, `all/write`, etc.)
  CHANGELOG.md
  docs/api.md
  setup.cfg
  src/ralph/api/auth/__init__.py
  src/ralph/api/auth/basic.py
  src/ralph/api/auth/oidc.py
  src/ralph/api/auth/user.py
  src/ralph/api/routers/statements.py
  src/ralph/conf.py
  tests/api/auth/test_basic.py
  tests/api/auth/test_oidc.py
  tests/api/test_statements_get.py
  tests/api/test_statements_post.py
  tests/api/test_statements_put.py
  tests/conftest.py
  tests/fixtures/auth.py
  tests/test_cli.py
  tests/test_conf.py
Labels: needs review, feature

#486 📝(project) unify infinitive use in docstrings
  gitlint/gitlint_emoji.py
  src/ralph/api/auth/basic.py
  src/ralph/api/routers/health.py
  src/ralph/api/routers/statements.py
  src/ralph/backends/data/s3.py
  src/ralph/backends/data/swift.py
  src/ralph/backends/mixins.py
  src/ralph/cli.py
  src/ralph/conf.py
  src/ralph/models/converter.py
  src/ralph/models/selector.py
  src/ralph/models/validator.py
  src/ralph/parsers.py
  tests/api/auth/test_basic.py
  tests/api/test_forwarding.py
  tests/api/test_statements.py
  tests/api/test_statements_get.py
  tests/api/test_statements_post.py
  tests/api/test_statements_put.py
  tests/backends/http/test_async_lrs.py
  tests/backends/lrs/test_async_mongo.py
  tests/backends/lrs/test_mongo.py
  tests/backends/stream/test_base.py
  tests/fixtures/backends.py
  tests/fixtures/hypothesis_strategies.py
  tests/helpers.py
  tests/models/edx/converters/xapi/test_base.py
  tests/models/edx/converters/xapi/test_video.py
  tests/models/edx/open_response_assessment/test_events.py
  tests/models/edx/peer_instruction/test_statements.py
  tests/models/test_converter.py
  tests/models/xapi/base/test_statements.py
  tests/models/xapi/test_video.py
  tests/models/xapi/test_virtual_classroom.py
  tests/test_cli.py
  tests/test_helpers.py
  tests/test_utils.py
Labels: improvement, needs review, easy pick
