Repository openfun/ralph, pull requests merged in 2023-06, with the labels that each got.

#342 💥(cli) Add mandatory "agent" field to credentials
  CHANGELOG.md
  Makefile
  docs/api.md
  src/ralph/api/__init__.py
  src/ralph/api/auth.py
  src/ralph/api/routers/statements.py
  src/ralph/backends/database/base.py
  src/ralph/backends/database/clickhouse.py
  src/ralph/backends/database/es.py
  src/ralph/backends/database/mongo.py
  src/ralph/cli.py
  tests/api/test_auth.py
  tests/api/test_statements_get.py
  tests/fixtures/auth.py
  tests/test_auth.py
  tests/test_cli.py
  tests/test_cli_usage.py
Labels: feature

#262 ✨(authentication) add OpenId Connect authentication
  .env.dist
  CHANGELOG.md
  docs/api.md
  setup.cfg
  src/ralph/api/__init__.py
  src/ralph/api/auth/__init__.py
  src/ralph/api/auth/basic.py
  src/ralph/api/auth/oidc.py
  src/ralph/api/auth/user.py
  src/ralph/api/routers/statements.py
  src/ralph/cli.py
  src/ralph/conf.py
  tests/api/auth/test_basic.py
  tests/api/auth/test_oidc.py
  tests/api/test_auth.py
  tests/api/test_forwarding.py
  tests/conftest.py
  tests/fixtures/__init__.py
  tests/fixtures/auth.py
  tests/test_auth.py
Labels: feature

#343 ✨(api) Add "mine" query parameter
  CHANGELOG.md
  docs/api.md
  src/ralph/api/auth.py
  src/ralph/api/routers/statements.py
  tests/api/test_statements_get.py
  tests/fixtures/auth.py
Labels: feature

#349 ⚡️(cli) allow to use a query for HTTP backends
  CHANGELOG.md
  src/ralph/cli.py
  tests/test_cli_usage.py
Labels: improvement, needs review

#226 Ora2 events
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/open_response_assessment/__init__.py
  src/ralph/models/edx/open_response_assessment/fields/__init__.py
  src/ralph/models/edx/open_response_assessment/fields/events.py
  src/ralph/models/edx/open_response_assessment/statements.py
  tests/models/edx/open_response_assessment/__init__.py
  tests/models/edx/open_response_assessment/test_events.py
  tests/models/edx/open_response_assessment/test_statements.py
Labels: needs review, feature

#368 ✨(models) add downloaded verb to tincan vocabulary
  CHANGELOG.md
  src/ralph/models/xapi/__init__.py
  src/ralph/models/xapi/concepts/verbs/tincan_vocabulary.py
  src/ralph/models/xapi/video/contexts.py
  src/ralph/models/xapi/video/statements.py
  tests/models/xapi/concepts/test_verbs.py
  tests/models/xapi/test_video.py
Labels: improvement

#369 🔖(minor) bump release to 3.8.0
  CHANGELOG.md
  arnold.yml
  setup.cfg
  src/helm/ralph/Chart.yaml
  src/ralph/__init__.py
  src/tray/tray.yml
Labels: needs review, FUN

#330 🏗️(backends) unify data backends swift
  src/ralph/backends/data/swift.py
  tests/backends/data/test_swift.py
  tests/conftest.py
  tests/fixtures/backends.py
Labels: needs review, feature

#313 296 helm feedback
  CHANGELOG.md
  src/helm/ralph/Chart.yaml
  src/helm/ralph/templates/deployment.yaml
  src/helm/ralph/templates/hpa.yaml
  src/helm/ralph/templates/ingress.yaml
  src/helm/ralph/templates/pvc.yml
  src/helm/ralph/templates/service.yaml
  src/helm/ralph/values.yaml
Labels: improvement
