Repository openfun/ralph, pull requests merged in 2023-12, with the labels that each got.

#531 🔧(project) add aliases for grouping extra dependencies
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  README.md
  docs/index.md
  pyproject.toml
Labels: improvement

#519 ✨(backends) split backend chunk size setting for read/write methods
  .env.dist
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/base.py
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/data/es.py
  src/ralph/backends/data/fs.py
  src/ralph/backends/data/ldp.py
  src/ralph/backends/data/mongo.py
  src/ralph/backends/data/s3.py
  src/ralph/backends/data/swift.py
  src/ralph/cli.py
  src/ralph/conf.py
  tests/backends/data/test_async_es.py
  tests/backends/data/test_async_mongo.py
  tests/backends/data/test_clickhouse.py
  tests/backends/data/test_es.py
  tests/backends/data/test_fs.py
  tests/backends/data/test_ldp.py
  tests/backends/data/test_mongo.py
  tests/backends/data/test_s3.py
  tests/backends/data/test_swift.py
  tests/fixtures/backends.py
  tests/test_cli.py
  tests/test_cli_usage.py
Labels: feature

#535 📝(project) improve main doc page and developer guide
  docs/index.md
  docs/tutorials/development_guide.md
  mkdocs.yml
Labels: improvement

#536 📝(project) improve documentation readability
  docs/contribute.md
  docs/index.md
  docs/tutorials/development_guide.md
Labels: improvement

#520 ✨(backends) add simultaneous option for AsyncWritable data backends
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/base.py
  src/ralph/backends/http/async_lrs.py
  tests/backends/data/test_async_es.py
  tests/backends/data/test_async_mongo.py
  tests/backends/data/test_base.py
  tests/backends/data/test_clickhouse.py
  tests/backends/data/test_es.py
  tests/backends/data/test_fs.py
  tests/backends/data/test_mongo.py
  tests/backends/data/test_s3.py
  tests/backends/data/test_swift.py
  tests/backends/http/test_async_lrs.py
Labels: feature

#538 🔨(project) use docker healthcheck for database services
  Makefile
  docker-compose.yml
Labels: improvement, needs review

#521 ✨(backends) add greedy option for data backends
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/base.py
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/data/es.py
  src/ralph/backends/data/fs.py
  src/ralph/backends/data/ldp.py
  src/ralph/backends/data/mongo.py
  src/ralph/backends/data/s3.py
  src/ralph/backends/data/swift.py
  tests/backends/data/test_async_es.py
  tests/backends/data/test_async_mongo.py
  tests/backends/data/test_base.py
  tests/backends/data/test_s3.py
Labels: feature

#524 🏗️(backends) migrate LRSHTTPBackend to LRSDataBackend
  .env.dist
  docs/backends/index.md
  src/ralph/backends/data/async_lrs.py
  src/ralph/backends/data/fs.py
  src/ralph/backends/data/lrs.py
  src/ralph/backends/http/async_lrs.py
  src/ralph/backends/http/base.py
  src/ralph/backends/http/lrs.py
  src/ralph/backends/loader.py
  src/ralph/cli.py
  tests/backends/data/test_async_lrs.py
  tests/backends/data/test_base.py
  tests/backends/http/__init__.py
  tests/backends/http/test_async_lrs.py
  tests/backends/http/test_base.py
  tests/backends/http/test_lrs.py
  tests/backends/test_loader.py
  tests/conftest.py
  tests/fixtures/backends.py
  tests/test_cli.py
  tests/test_cli_usage.py
  tests/test_dependencies.py
Labels: feature

#526 🏗️(backends) migrate WSStreamBackend to AsyncWSDataBackend
  docs/backends/index.md
  src/ralph/backends/data/async_ws.py
  src/ralph/backends/data/base.py
  src/ralph/backends/http/__init__.py
  src/ralph/backends/loader.py
  src/ralph/backends/stream/__init__.py
  src/ralph/backends/stream/base.py
  src/ralph/backends/stream/ws.py
  src/ralph/cli.py
  src/ralph/utils.py
  tests/backends/data/test_async_ws.py
  tests/backends/data/test_base.py
  tests/backends/stream/__init__.py
  tests/backends/stream/test_base.py
  tests/backends/stream/test_ws.py
  tests/backends/test_loader.py
  tests/backends/test_utils_backends/valid_backends.py
  tests/fixtures/backends.py
  tests/test_cli.py
  tests/test_cli_usage.py
Labels: feature

#533 🏗️(backends) remove Loggable and logger injection
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_lrs.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/async_ws.py
  src/ralph/backends/data/base.py
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/data/es.py
  src/ralph/backends/data/fs.py
  src/ralph/backends/data/ldp.py
  src/ralph/backends/data/lrs.py
  src/ralph/backends/data/mixins.py
  src/ralph/backends/data/mongo.py
  src/ralph/backends/data/s3.py
  src/ralph/backends/data/swift.py
  src/ralph/backends/lrs/async_es.py
  src/ralph/backends/lrs/async_mongo.py
  src/ralph/backends/lrs/clickhouse.py
  src/ralph/backends/lrs/es.py
  src/ralph/backends/lrs/fs.py
  src/ralph/backends/lrs/mongo.py
  src/ralph/utils.py
  tests/api/test_statements_get.py
  tests/backends/data/test_async_es.py
  tests/backends/data/test_async_lrs.py
  tests/backends/data/test_async_mongo.py
  tests/backends/data/test_async_ws.py
  tests/backends/data/test_base.py
  tests/backends/data/test_clickhouse.py
  tests/backends/data/test_es.py
  tests/backends/data/test_fs.py
  tests/backends/data/test_mongo.py
  tests/backends/data/test_s3.py
Labels: improvement

#527 ✨(backends) replace archive cli argument with query (rebased)
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_lrs.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/async_ws.py
  src/ralph/backends/data/base.py
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/data/es.py
  src/ralph/backends/data/fs.py
  src/ralph/backends/data/ldp.py
  src/ralph/backends/data/lrs.py
  src/ralph/backends/data/mongo.py
  src/ralph/backends/data/s3.py
  src/ralph/backends/data/swift.py
  src/ralph/backends/lrs/async_es.py
  src/ralph/backends/lrs/async_mongo.py
  src/ralph/backends/lrs/clickhouse.py
  src/ralph/backends/lrs/es.py
  src/ralph/backends/lrs/mongo.py
  src/ralph/cli.py
  tests/backends/data/test_async_es.py
  tests/backends/data/test_async_mongo.py
  tests/backends/data/test_base.py
  tests/backends/data/test_es.py
  tests/backends/data/test_fs.py
  tests/backends/data/test_ldp.py
  tests/backends/data/test_mongo.py
  tests/backends/data/test_s3.py
  tests/backends/data/test_swift.py
  tests/backends/lrs/test_async_es.py
  tests/backends/lrs/test_async_mongo.py
  tests/backends/lrs/test_clickhouse.py
  tests/backends/lrs/test_es.py
  tests/backends/lrs/test_mongo.py
  tests/fixtures/backends.py
  tests/test_cli.py
  tests/test_cli_usage.py
Labels: improvement, needs review

#542 💚(circle) prevent executing jobs for PyPi pre-release tags
  .circleci/config.yml
Labels: improvement, needs review

#544 🔖(prerelease) bump release to 4.0.0-beta1
  src/ralph/__init__.py
Labels: release
