Repository openfun/ralph, pull requests merged in 2023-05, with the labels that each got.

#319 🧑‍💻(project) add Discord server link
  README.md
Labels: needs review, easy pick

#316 🐛(api) fix `more` irl on second request
  CHANGELOG.md
  src/ralph/api/routers/statements.py
  tests/api/test_statements_get.py
Labels: critical, needs review, bug

#327 🔧(project) improve sentry integration
  .env.dist
  CHANGELOG.md
  docs/api.md
  src/helm/ralph/templates/deployment.yaml
  src/helm/ralph/values.yaml
  src/ralph/api/__init__.py
  src/ralph/conf.py
  src/tray/templates/services/app/deploy.yml.j2
  src/tray/vars/all/main.yml
Labels: improvement

#332 🔖(minor) bump release to 3.6.0
  CHANGELOG.md
  arnold.yml
  setup.cfg
  src/helm/ralph/Chart.yaml
  src/ralph/__init__.py
  src/tray/tray.yml
Labels: needs review, release, FUN

#331 Add all Inverse Functional Identifier support for filtering by `agent`
  CHANGELOG.md
  src/ralph/api/routers/statements.py
  src/ralph/backends/database/base.py
  src/ralph/backends/database/clickhouse.py
  src/ralph/backends/database/es.py
  src/ralph/backends/database/mongo.py
  tests/api/test_statements_get.py
Labels: improvement

#333 💚(circle) display test coverage in ci
  setup.cfg
Labels: improvement, FUN
