Repository openfun/ralph, pull requests merged in 2023-11, with the labels that each got.

#493 ♻️(backends) remove ClickHouse JSON column (#482)
  .env.dist
  CHANGELOG.md
  UPGRADE.md
  docs/backends.md
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/lrs/clickhouse.py
  tests/backends/data/test_clickhouse.py
  tests/backends/lrs/test_clickhouse.py
  tests/fixtures/backends.py
Labels: improvement, breaking change

#497 🐛(Makefile) add missing backslash
  Makefile
Labels: bug

#490 ⚡️(cli) lazy backend options
  src/ralph/cli.py
  tests/test_cli.py
Labels: improvement

#496 🔧(project) switch from setup.cfg to pyproject.toml
  pyproject.toml
  setup.cfg
Labels: improvement, needs review

#503 ✅(api) fix slow tests
  tests/api/test_statements_get.py
Labels: improvement, needs review

#502 🔥(project) remove remaining pylint warnings escapes
  src/ralph/backends/lrs/base.py
  src/ralph/cli.py
  tests/backends/lrs/test_async_es.py
  tests/backends/lrs/test_async_mongo.py
  tests/backends/lrs/test_clickhouse.py
  tests/backends/lrs/test_es.py
  tests/backends/lrs/test_fs.py
  tests/backends/lrs/test_mongo.py
  tests/backends/test_utils_backends/valid_backends.py
Labels: improvement, needs review

#500 🚚(backends) rename query_model to query_class
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/base.py
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/data/es.py
  src/ralph/backends/data/mongo.py
  tests/backends/data/test_async_es.py
  tests/backends/data/test_async_mongo.py
  tests/backends/data/test_clickhouse.py
  tests/backends/data/test_es.py
  tests/backends/data/test_fs.py
  tests/backends/data/test_ldp.py
  tests/backends/data/test_mongo.py
  tests/backends/data/test_s3.py
  tests/backends/data/test_swift.py
Labels: easy pick

#507 🔧(project) add flake8-fixme set of rules for Ruff
  pyproject.toml
Labels: improvement, needs review

#506 🎨(tests) standardize naming for backend tests
  tests/backends/data/test_async_es.py
  tests/backends/data/test_async_mongo.py
  tests/backends/data/test_clickhouse.py
  tests/backends/data/test_es.py
  tests/backends/data/test_fs.py
  tests/backends/data/test_ldp.py
  tests/backends/data/test_mongo.py
  tests/backends/data/test_s3.py
  tests/backends/data/test_swift.py
  tests/backends/http/test_async_lrs.py
  tests/backends/http/test_lrs.py
  tests/backends/lrs/test_async_es.py
  tests/backends/lrs/test_async_mongo.py
  tests/backends/lrs/test_clickhouse.py
  tests/backends/lrs/test_es.py
  tests/backends/lrs/test_fs.py
  tests/backends/lrs/test_mongo.py
  tests/backends/stream/test_ws.py
Labels: improvement, needs review, easy pick

#514 ✅(api) enhance limit query parameter validation
  CHANGELOG.md
  src/ralph/api/routers/statements.py
  tests/api/test_statements_get.py
Labels: improvement

#499 🔖(helm) bump chart release to 0.2.0
  src/helm/ralph/Chart.yaml
Labels: needs review, FUN

#508 📝(project) add a specific CHANGELOG.md for the helm chart
  CHANGELOG.md
  src/helm/CHANGELOG.md
Labels: improvement, needs review

#473 ✨ (api) Allow multiple authentication methods (oidc & basic)
  .env.dist
  CHANGELOG.md
  docs/api.md
  docs/backends.md
  src/ralph/api/auth/__init__.py
  src/ralph/api/auth/basic.py
  src/ralph/api/auth/oidc.py
  src/ralph/backends/data/es.py
  src/ralph/cli.py
  src/ralph/conf.py
  tests/api/auth/test_basic.py
  tests/api/auth/test_oidc.py
  tests/api/test_statements_get.py
  tests/api/test_statements_post.py
  tests/api/test_statements_put.py
  tests/conftest.py
  tests/fixtures/auth.py
  tests/helpers.py
  tests/test_conf.py
Labels: needs review

#501 ✨(backends) generic data backends
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/base.py
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/data/es.py
  src/ralph/backends/data/fs.py
  src/ralph/backends/data/ldp.py
  src/ralph/backends/data/mongo.py
  src/ralph/backends/data/s3.py
  src/ralph/backends/data/swift.py
  src/ralph/backends/lrs/async_es.py
  src/ralph/backends/lrs/async_mongo.py
  src/ralph/backends/lrs/base.py
  src/ralph/backends/lrs/clickhouse.py
  src/ralph/backends/lrs/es.py
  src/ralph/backends/lrs/fs.py
  src/ralph/backends/lrs/mongo.py
  tests/backends/data/test_base.py
Labels: improvement, needs review

#528 🎨(api) improve heartbeat endpoint
  src/ralph/api/routers/health.py
Labels: improvement, needs review

#529 💥(project) drop support for python3.7 and unpin dependencies
  .circleci/config.yml
  CHANGELOG.md
  pyproject.toml
Labels: breaking change

#510 ♻️(backends) use common utilities among backends
  CHANGELOG.md
  pyproject.toml
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/base.py
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/data/es.py
  src/ralph/backends/data/fs.py
  src/ralph/backends/data/ldp.py
  src/ralph/backends/data/mongo.py
  src/ralph/backends/data/s3.py
  src/ralph/backends/data/swift.py
  src/ralph/backends/http/async_lrs.py
  src/ralph/cli.py
  src/ralph/utils.py
  tests/backends/data/test_async_es.py
  tests/backends/data/test_async_mongo.py
  tests/backends/data/test_clickhouse.py
  tests/backends/data/test_es.py
  tests/backends/data/test_fs.py
  tests/backends/data/test_ldp.py
  tests/backends/data/test_mongo.py
  tests/backends/data/test_s3.py
  tests/backends/data/test_swift.py
  tests/backends/http/test_async_lrs.py
Labels: improvement, needs review

#511 ♻️(backends) add logger property to data/lrs backends
  src/ralph/backends/data/async_es.py
  src/ralph/backends/data/async_mongo.py
  src/ralph/backends/data/base.py
  src/ralph/backends/data/clickhouse.py
  src/ralph/backends/data/es.py
  src/ralph/backends/data/fs.py
  src/ralph/backends/data/ldp.py
  src/ralph/backends/data/mixins.py
  src/ralph/backends/data/mongo.py
  src/ralph/backends/data/s3.py
  src/ralph/backends/data/swift.py
  src/ralph/backends/lrs/async_es.py
  src/ralph/backends/lrs/async_mongo.py
  src/ralph/backends/lrs/clickhouse.py
  src/ralph/backends/lrs/es.py
  src/ralph/backends/lrs/fs.py
  src/ralph/backends/lrs/mongo.py
  tests/api/test_statements_get.py
  tests/backends/data/test_async_es.py
  tests/backends/data/test_base.py
  tests/backends/data/test_es.py
  tests/backends/data/test_mixins.py
  tests/fixtures/backends.py
Labels: improvement
