Repository openfun/ralph, pull requests merged in 2023-02, with the labels that each got.

#266 🏷️(library) restore python 3.7+ compatibility for models
  .circleci/config.yml
  CHANGELOG.md
  src/ralph/conf.py
  src/ralph/models/edx/base.py
  src/ralph/models/edx/browser.py
  src/ralph/models/edx/enrollment/fields/contexts.py
  src/ralph/models/edx/enrollment/fields/events.py
  src/ralph/models/edx/enrollment/statements.py
  src/ralph/models/edx/navigational/statements.py
  src/ralph/models/edx/problem_interaction/fields/events.py
  src/ralph/models/edx/problem_interaction/statements.py
  src/ralph/models/edx/server.py
  src/ralph/models/edx/textbook_interaction/fields/events.py
  src/ralph/models/edx/textbook_interaction/statements.py
  src/ralph/models/edx/video/fields/events.py
  src/ralph/models/edx/video/statements.py
  src/ralph/models/selector.py
  src/ralph/models/xapi/base.py
  src/ralph/models/xapi/constants.py
  src/ralph/models/xapi/fields/actors.py
  src/ralph/models/xapi/fields/common.py
  src/ralph/models/xapi/fields/contexts.py
  src/ralph/models/xapi/fields/objects.py
  src/ralph/models/xapi/fields/results.py
  src/ralph/models/xapi/fields/unnested_objects.py
  src/ralph/models/xapi/fields/verbs.py
  src/ralph/models/xapi/navigation/fields/objects.py
  src/ralph/models/xapi/video/constants.py
  src/ralph/models/xapi/video/fields/contexts.py
  src/ralph/models/xapi/video/fields/objects.py
  src/ralph/models/xapi/video/fields/results.py
  src/ralph/models/xapi/video/fields/verbs.py
  src/ralph/utils.py
Labels: improvement, needs review

#267 🔖(minor) bump release to 3.3.0
  CHANGELOG.md
  setup.cfg
  src/ralph/__init__.py
  src/tray/tray.yml
Labels: release, FUN

#269 📝(project) correct minor issue in documentation
  docs/api.md
  docs/index.md
Labels: improvement

#271 📝(docs) update copyright holder
  LICENSE.md
  mkdocs.yml
Labels: improvement, easy pick
