Repository openfun/ralph, pull requests merged in 2023-08, with the labels that each got.

#336 🏗️(backends) unify data backends es
  docker-compose.yml
  src/ralph/backends/data/base.py
  src/ralph/backends/data/es.py
  src/ralph/backends/lrs/base.py
  src/ralph/backends/lrs/es.py
  src/ralph/conf.py
  tests/api/test_statements.py
  tests/backends/data/test_base.py
  tests/backends/data/test_es.py
  tests/backends/lrs/test_es.py
  tests/conftest.py
  tests/fixtures/backends.py
  tests/test_conf.py
Labels: needs review, feature

#365 🏗️(backends) unify data backends fs lrs
  src/ralph/backends/data/fs.py
  src/ralph/backends/lrs/base.py
  src/ralph/backends/lrs/fs.py
  tests/backends/data/test_base.py
  tests/backends/lrs/test_fs.py
  tests/conftest.py
  tests/fixtures/backends.py
Labels: needs review, feature

#409 📝(auth) fix user credentials creation documentation
  docs/api.md
Labels: improvement, easy pick

#406 👷(project) ensure renovate configuration file is valid
  .circleci/config.yml
Labels: improvement, easy pick

#399 (api) Return 400 status on invalid parameter in `/statements`
  CHANGELOG.md
  src/ralph/api/forwarding.py
  src/ralph/api/routers/statements.py
  tests/api/test_forwarding.py
  tests/api/test_statements_get.py
  tests/api/test_statements_post.py
  tests/api/test_statements_put.py
Labels: improvement

#385 🦺(models) make ProfileActivity presence mandatory
  CHANGELOG.md
  src/ralph/models/edx/converters/xapi/video.py
  src/ralph/models/xapi/video/contexts.py
  src/ralph/models/xapi/video/statements.py
  src/ralph/models/xapi/virtual_classroom/contexts.py
  tests/models/edx/converters/xapi/test_video.py
  tests/models/xapi/test_video.py
  tests/models/xapi/test_virtual_classroom.py
Labels: bug

#402 (api) disable lrshttp when called in events loop
  CHANGELOG.md
  src/ralph/backends/http/lrs.py
  tests/backends/http/test_lrs.py
Labels: improvement, needs review, needs test

#422 (backend) Add `max_statements` to read in LRSHTTP
  CHANGELOG.md
  src/ralph/backends/http/async_lrs.py
  src/ralph/backends/http/base.py
  tests/backends/http/test_async_lrs.py
  tests/backends/http/test_base.py
Labels: improvement
