Repository openfun/ralph, pull requests merged in 2024-02, with the labels that each got.

#564 💚(circle) change deprecated ubuntu machines
  .circleci/config.yml
Labels: dependencies

#563 📝(helm) add helm README tutorial to documentation
  docs/tutorials/helm.md
  docs/tutorials/lrs/index.md
  mkdocs.yml
  src/helm/README.md
Labels: improvement

#565 🔖(helm) bump release to 0.3.0
  src/helm/CHANGELOG.md
  src/helm/ralph/Chart.yaml
Labels: release

#567 💚(helm) fix helm publication job
  .circleci/config.yml
Labels: bug

#568 🔖(minor) bump release to 4.1.0
  CHANGELOG.md
  UPGRADE.md
  src/helm/CHANGELOG.md
  src/helm/ralph/Chart.yaml
  src/ralph/__init__.py
  src/tray/tray.yml
Labels: release

#569 🔖(helm) bump release to 0.4.0
  src/helm/CHANGELOG.md
  src/helm/ralph/Chart.yaml
Labels: release, helm

#562 🐛(backends) disallow namespace package discovery
  CHANGELOG.md
  pyproject.toml
  src/ralph/backends/loader.py
  src/ralph/conf.py
  tests/backends/test_loader.py
  tests/backends/test_utils_backends/valid_backends.py
Labels: bug
