Repository openfun/ralph, pull requests merged in 2024-04, with the labels that each got.

#578 ✨(models) add Edx cohort statements
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/cohort/__init__.py
  src/ralph/models/edx/cohort/fields/__init__.py
  src/ralph/models/edx/cohort/fields/events.py
  src/ralph/models/edx/cohort/statements.py
  tests/models/edx/cohort/__init__.py
  tests/models/edx/cohort/test_statements.py
Labels: needs review, feature, easy pick

#575 ✨(models) add Edx drag and drop statements
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/drag_and_drop/__init__.py
  src/ralph/models/edx/drag_and_drop/fields/__init__.py
  src/ralph/models/edx/drag_and_drop/fields/events.py
  src/ralph/models/edx/drag_and_drop/statements.py
  tests/models/edx/drag_and_drop/__init__.py
  tests/models/edx/drag_and_drop/test_statements.py
Labels: needs review, feature

#574 ✨(models) add Edx course content completion statements
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/course_content_completion/__init__.py
  src/ralph/models/edx/course_content_completion/fields/__init__.py
  src/ralph/models/edx/course_content_completion/fields/events.py
  src/ralph/models/edx/course_content_completion/statements.py
  tests/models/edx/course_content_completion/__init__.py
  tests/models/edx/course_content_completion/test_statements.py
Labels: needs review, feature, easy pick

#573 ✨(models) add Edx poll and survey statements
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/poll/__init__.py
  src/ralph/models/edx/poll/fields/__init__.py
  src/ralph/models/edx/poll/fields/events.py
  src/ralph/models/edx/poll/statements.py
  src/ralph/models/edx/survey/__init__.py
  src/ralph/models/edx/survey/fields/__init__.py
  src/ralph/models/edx/survey/fields/events.py
  src/ralph/models/edx/survey/statements.py
  tests/models/edx/poll/__init__.py
  tests/models/edx/poll/test_statements.py
  tests/models/edx/survey/__init__.py
  tests/models/edx/survey/test_statements.py
Labels: needs review, feature

#576 ✨(models) add Edx bookmark statements
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/bookmark/__init__.py
  src/ralph/models/edx/bookmark/fields/__init__.py
  src/ralph/models/edx/bookmark/fields/events.py
  src/ralph/models/edx/bookmark/statements.py
  tests/models/edx/bookmark/__init__.py
  tests/models/edx/bookmark/test_events.py
  tests/models/edx/bookmark/test_statements.py
Labels: needs review, feature

#580 ✨(models) add Edx certificate statements
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/certificate/__init__.py
  src/ralph/models/edx/certificate/fields/__init__.py
  src/ralph/models/edx/certificate/fields/events.py
  src/ralph/models/edx/certificate/statements.py
  tests/models/edx/certificate/__init__.py
  tests/models/edx/certificate/test_events.py
  tests/models/edx/certificate/test_statements.py
Labels: needs review, feature

#584 🐛(api) fix activity querying for statements with object missing a type
  CHANGELOG.md
  src/ralph/backends/lrs/clickhouse.py
  src/ralph/backends/lrs/es.py
  src/ralph/backends/lrs/mongo.py
  tests/backends/lrs/test_async_es.py
  tests/backends/lrs/test_async_mongo.py
  tests/backends/lrs/test_clickhouse.py
  tests/backends/lrs/test_es.py
  tests/backends/lrs/test_fs.py
  tests/backends/lrs/test_mongo.py
  tests/helpers.py
Labels: bug

#581 ✨(models) add Edx notes statements
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/notes/__init__.py
  src/ralph/models/edx/notes/fields/__init__.py
  src/ralph/models/edx/notes/fields/events.py
  src/ralph/models/edx/notes/statements.py
  tests/models/edx/notes/__init__.py
  tests/models/edx/notes/test_events.py
  tests/models/edx/notes/test_statements.py
Labels: needs review, feature

#582 ✨(models) add Edx teams-related statements
  CHANGELOG.md
  src/ralph/models/edx/__init__.py
  src/ralph/models/edx/teams_related/__init__.py
  src/ralph/models/edx/teams_related/fields/__init__.py
  src/ralph/models/edx/teams_related/fields/events.py
  src/ralph/models/edx/teams_related/statements.py
  tests/models/edx/teams_related/__init__.py
  tests/models/edx/teams_related/test_events.py
  tests/models/edx/teams_related/test_statements.py
Labels: needs review, feature

#586 🔖(minor) bump release to 4.2.0
  CHANGELOG.md
  src/helm/CHANGELOG.md
  src/helm/ralph/Chart.yaml
  src/ralph/__init__.py
  src/tray/tray.yml
Labels: release

#570 💚(circle) test helm with ralph build image
  .circleci/config.yml
Labels: WIP, helm

#588 👽️(project) replace deprecated `parse_obj_as`
  CHANGELOG.md
  src/ralph/backends/data/async_lrs.py
  src/ralph/backends/data/lrs.py
  src/ralph/conf.py
  tests/api/auth/test_oidc.py
  tests/backends/data/test_async_lrs.py
  tests/backends/data/test_async_ws.py
  tests/fixtures/backends.py
  tests/test_conf.py
Labels: improvement

#591 🔧(dependencies) update ignored dependencies in renovate configuration
  .gitignore
  renovate.json
Labels: needs review, easy pick

#589 🎨(api) use Annotated instead of Query as the default value
  src/ralph/api/routers/statements.py
Labels: improvement

#594 ♻️(models) set missing default values for xAPI activity types
  src/ralph/models/xapi/concepts/activity_types/acrossx_profile.py
  src/ralph/models/xapi/concepts/activity_types/activity_streams_vocabulary.py
  src/ralph/models/xapi/concepts/activity_types/audio.py
  src/ralph/models/xapi/concepts/activity_types/tincan_vocabulary.py
Labels: easy pick
